### ISSUE TITLE
Знайти фото Нового Роздолу в Інтернеті

### ISSUE THREAD

**Issue by botiko1** [botiko1/pr4.2020#1]
Знайти найкраще фото в Інтернеті

**Comment by Guziy1** [comment]
![depositphotos_78791224-stock-photo-bonobo-monkey-lying-on-grass](https://user-images.githubusercontent.com/74353312/98930337-8e689600-24ed-11eb-9332-b8d4e665d3a7.jpg)

**Comment by botiko1** [comment]
Мавпа не підходить

**Comment by Guziy1** [comment]
![Без названия](https://user-images.githubusercontent.com/74353312/98930680-05059380-24ee-11eb-9b89-bb45b3182b3c.jpg)

**Comment by botiko1** [comment]
Знайшов
